[package]
name    = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow     = "1.0.79"
clap       = { version = "4.4.18", features = ["derive"] }
env_logger = "0.11.1"
form       = "0.11.1"
log        = "0.4.20"
semver     = "1.0.21"
strum      = { version = "0.26.1", features = ["derive"] }
svd2rust   = { version = "0.32.0", default-features = false }
svdtools   = "0.3.11"
toml_edit  = "0.22.4"
