[package]
name    = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow     = "1.0.81"
clap       = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.3"
form       = "0.11.1"
log        = "0.4.21"
semver     = "1.0.22"
strum      = { version = "0.26.2", features = ["derive"] }
svd2rust   = { git = "https://github.com/rust-embedded/svd2rust", branch = "fmt", default-features = false }
svdtools   = "0.3.14"
toml_edit  = "0.22.9"
